### ISSUE TITLE
problem with build

### ISSUE THREAD

**Issue by greezly** [clipperz/password-manager#39]
Hello,

I'm getting the following error when I want to build:
./scripts/build clean install debug --frontends beta --backends php
Traceback (most recent call last):
  File "/root/clipperz-password-manager-36ff1de/scripts/builder/main.py", line 177, in <module>
    main()
  File "/root/clipperz-password-manager-36ff1de/scripts/builder/main.py", line 171, in main
    build(settings, currentRepository)
  File "/root/clipperz-password-manager-36ff1de/scripts/builder/main.py", line 94, in build
    frontends.append(frontendBuilder.FrontendBuilder(frontend, loadSettings('frontend', frontend), repository.version()))
  File "/root/clipperz-password-manager-36ff1de/scripts/builder/repository.py", line 44, in version
    result = self.revision()
  File "/root/clipperz-password-manager-36ff1de/scripts/builder/repository.py", line 62, in revision
    return self.repository.commits()[0].id
AttributeError: 'Repo' object has no attribute 'commits'

I'm using centos 6.2, python 2.7, GitPython 0.3.2
Could you help me?

Thank you!

**Comment by gcsolaroli** [comment]
Cleaning up some old neglected issues.
