### ISSUE TITLE
Problems building with possible solution?

### ISSUE THREAD

**Issue by llynix** [clipperz/password-manager#70]
I had problems building on Ubuntu 12.04:

Traceback (most recent call last):
  File "/home/llynix/Desktop/Web/password-manager/scripts/builder/main.py", line 197, in <module>
    main()
  File "/home/llynix/Desktop/Web/password-manager/scripts/builder/main.py", line 191, in main
    build(settings, currentRepository)
  File "/home/llynix/Desktop/Web/password-manager/scripts/builder/main.py", line 105, in build
    builder = builderClass(frontend, loadSettings('frontend', frontend), repository.version())
  File "/home/llynix/Desktop/Web/password-manager/scripts/builder/repository.py", line 48, in version
    result = self.revision()
  File "/home/llynix/Desktop/Web/password-manager/scripts/builder/repository.py", line 65, in revision
    return self.repository.commits()[0].id

  File "/usr/lib/pymodules/python2.7/git/repo.py", line 127, in commits
    return Commit.find_all(self, start, path, **options)
  File "/usr/lib/pymodules/python2.7/git/commit.py", line 132, in find_all
    return cls.list_from_string(repo, output)
  File "/usr/lib/pymodules/python2.7/git/commit.py", line 159, in list_from_string
    author, authored_date = cls.actor(lines.pop(0))
  File "/usr/lib/pymodules/python2.7/git/commit.py", line 253, in actor
    actor, epoch = m.groups()
AttributeError: 'NoneType' object has no attribute 'groups'

I managed to get it to build by replacing 'repository.version' with '1' at around line 205 in main.py:
# builder = builderClass(frontend, loadSettings('frontend', frontend), repository.version())

```
            builder = builderClass(frontend, loadSettings('frontend', frontend), '1')
```

Not sure if this caused any problems.

**Comment by llynix** [comment]
Both these issues seem to be related:
https://github.com/clipperz/password-manager/issues/59
https://github.com/clipperz/password-manager/issues/39

**Comment by gcsolaroli** [comment]
Cleaning up some old neglected issues.
